name: status_saver
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^0.1.1

  cupertino_icons: ^0.1.3
  share: ^0.6.5
  url_launcher: ^5.5.3
  permission_handler: ^5.0.1+1
  flutter_staggered_grid_view: ^0.3.2
  path_provider: ^1.6.14
  image_gallery_saver: ^1.5.0
  flutter_html: ^1.0.2
  flutter_fab_dialer: ^0.1.1
  thumbnails: ^1.0.1
  chewie: ^0.9.10
  video_player: ^0.10.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/video_loader.gif

